### ISSUE TITLE
[ERROR] [launch]: Caught exception in launch (see debug for traceback): executable 'vmap_node' not found on the libexec directory '/home/user/flock2_ws/install/fiducial_vlam/lib/fiducial_vlam' 

### ISSUE THREAD

**Issue by sunnysolution1618** [clydemcqueen/flock2#45]
Hi, this is Sunny.

First of all, thank you very much for sharing such an amazing project ~

However, when I run the code, the following errors occured:

user@ubuntu:~/flock2_ws$ ros2 launch flock2 launch_one.py
[INFO] [launch]: All log files can be found below /home/user/.ros/log/2020-10-04-14-58-29-976416-ubuntu-12869
[INFO] [launch]: Default logging verbosity is set to INFO
[ERROR] [launch]: Caught exception in launch (see debug for traceback): executable 'vmap_node' not found on the libexec directory '/home/user/flock2_ws/install/fiducial_vlam/lib/fiducial_vlam' 
Task exception was never retrieved
future: <Task finished coro=<LaunchService._process_one_event() done, defined at /opt/ros/eloquent/lib/python3.6/site-packages/launch/launch_service.py:293> exception=RuntimeError('Signal event received before subprocess transport available.',)>
Traceback (most recent call last):
  File "/opt/ros/eloquent/lib/python3.6/site-packages/launch/launch_service.py", line 295, in _process_one_event
    await self.__process_event(next_event)
  File "/opt/ros/eloquent/lib/python3.6/site-packages/launch/launch_service.py", line 315, in __process_event
    visit_all_entities_and_collect_futures(entity, self.__context))
  File "/opt/ros/eloquent/lib/python3.6/site-packages/launch/utilities/visit_all_entities_and_collect_futures_impl.py", line 38, in visit_all_entities_and_collect_futures
    sub_entities = entity.visit(context)
  File "/opt/ros/eloquent/lib/python3.6/site-packages/launch/action.py", line 108, in visit
    return self.execute(context)
  File "/opt/ros/eloquent/lib/python3.6/site-packages/launch/actions/opaque_function.py", line 75, in execute
    return self.__function(context, *self.__args, **self.__kwargs)
  File "/opt/ros/eloquent/lib/python3.6/site-packages/launch/actions/execute_process.py", line 383, in __on_signal_process_event
    raise RuntimeError('Signal event received before subprocess transport available.')
RuntimeError: Signal event received before subprocess transport available.
[INFO] [rviz2-1]: process started with pid [12885]
[INFO] [robot_state_publisher-2]: process started with pid [12886]
[INFO] [tello_driver_main-3]: process started with pid [12887]
[INFO] [joy_node-4]: process started with pid [12888]
[INFO] [flock_base-5]: process started with pid [12889]
[INFO] [drone_base-6]: process started with pid [12890]
Task exception was never retrieved
future: <Task finished coro=<LaunchService._process_one_event() done, defined at /opt/ros/eloquent/lib/python3.6/site-packages/launch/launch_service.py:293> exception=RuntimeError('Signal event received before subprocess transport available.',)>
Traceback (most recent call last):
  File "/opt/ros/eloquent/lib/python3.6/site-packages/launch/launch_service.py", line 295, in _process_one_event
    await self.__process_event(next_event)
  File "/opt/ros/eloquent/lib/python3.6/site-packages/launch/launch_service.py", line 315, in __process_event
    visit_all_entities_and_collect_futures(entity, self.__context))
  File "/opt/ros/eloquent/lib/python3.6/site-packages/launch/utilities/visit_all_entities_and_collect_futures_impl.py", line 38, in visit_all_entities_and_collect_futures
    sub_entities = entity.visit(context)
  File "/opt/ros/eloquent/lib/python3.6/site-packages/launch/action.py", line 108, in visit
    return self.execute(context)
  File "/opt/ros/eloquent/lib/python3.6/site-packages/launch/actions/opaque_function.py", line 75, in execute
    return self.__function(context, *self.__args, **self.__kwargs)
  File "/opt/ros/eloquent/lib/python3.6/site-packages/launch/actions/execute_process.py", line 383, in __on_signal_process_event
    raise RuntimeError('Signal event received before subprocess transport available.')
RuntimeError: Signal event received before subprocess transport available.
[INFO] [joy_node-4]: sending signal 'SIGINT' to process[joy_node-4]
[INFO] [tello_driver_main-3]: sending signal 'SIGINT' to process[tello_driver_main-3]
[INFO] [robot_state_publisher-2]: sending signal 'SIGINT' to process[robot_state_publisher-2]
[INFO] [rviz2-1]: sending signal 'SIGINT' to process[rviz2-1]
[ERROR] [tello_driver_main-3]: process has died [pid 12887, exit code -2, cmd '/home/user/flock2_ws/install/tello_driver/lib/tello_driver/tello_driver_main --ros-args -r __node:=tello_driver -r __ns:=/solo'].
[ERROR] [rviz2-1]: process has died [pid 12885, exit code -2, cmd 'rviz2 -d install/flock2/share/flock2/launch/one.rviz'].
[INFO] [joy_node-4]: process has finished cleanly [pid 12888]
[flock_base-5] [INFO] [flock_base]: FlockBase Parameters
[flock_base-5] [INFO] [flock_base]: drones = [solo]
[flock_base-5] [INFO] [flock_base]: 1 drone
[drone_base-6] [INFO] [solo.drone_base]: DroneBase Parameters
[drone_base-6] [INFO] [solo.drone_base]: flight_data_timeout_sec = 1.500000
[drone_base-6] [INFO] [solo.drone_base]: odom_timeout_sec = 1.500000
[drone_base-6] [INFO] [solo.drone_base]: FlightControllerSimple Parameters
[drone_base-6] [INFO] [solo.drone_base]: stabilize_time_sec = 5.000000
[robot_state_publisher-2] Initialize urdf model from file: /home/user/flock2_ws/install/tello_description/share/tello_description/urdf/tello.urdf
[robot_state_publisher-2] Parsing robot urdf xml string.
[robot_state_publisher-2] The root link base_link has an inertia specified in the URDF, but KDL does not support a root link with an inertia.  As a workaround, you can add an extra dummy link to your URDF.
[robot_state_publisher-2] Link camera_link had 0 children
[robot_state_publisher-2] got segment base_link
[robot_state_publisher-2] got segment camera_link
[robot_state_publisher-2] Adding fixed segment from base_link to camera_link
[joy_node-4] [ERROR] [joy_node]: Couldn't open joystick /dev/input/js0. Will retry every second.
[INFO] [robot_state_publisher-2]: process has finished cleanly [pid 12886]
[drone_base-6] [INFO] [solo.drone_base]: drone initialized
[joy_node-4] [INFO] [rclcpp]: signal_handler(signal_value=2)
[joy_node-4] [INFO] [joy_node]: joy_node shut down.
[robot_state_publisher-2] [INFO] [rclcpp]: signal_handler(signal_value=2)
[ERROR] [drone_base-6]: process[drone_base-6] failed to terminate '5' seconds after receiving 'SIGINT', escalating to 'SIGTERM'
[ERROR] [flock_base-5]: process[flock_base-5] failed to terminate '5' seconds after receiving 'SIGINT', escalating to 'SIGTERM'
[INFO] [drone_base-6]: sending signal 'SIGTERM' to process[drone_base-6]
[INFO] [flock_base-5]: sending signal 'SIGTERM' to process[flock_base-5]
[ERROR] [drone_base-6]: process has died [pid 12890, exit code -15, cmd '/home/user/tello_ros_ws/install/flock2/lib/flock2/drone_base --ros-args -r __node:=drone_base -r __ns:=/solo'].
[ERROR] [flock_base-5]: process has died [pid 12889, exit code -15, cmd '/home/user/tello_ros_ws/install/flock2/lib/flock2/flock_base --ros-args'].

It seems the vmap_node is missing. Can know how to solve this issue ?

Thank you very much.

Best regards,
Sunny

**Comment by Elessar008** [comment]
Hello!
Thank you very much for sharing this project. With your help, I have learned a lot. Thanks again for your help！
However，when I tried to launch the flock2 launch_one.py, I met the same error like Sunny. Could you please give me some guidance to solve this problem?
Thank you for your help!

Best wishes,
Elessar008

**Comment by clydemcqueen** [comment]
Without doing much investigation, I believe that the launch file needs to be updated to invoke vmap_main and vloc_main instead of vmap_node and vloc_node. I will run tests and confirm.

**Comment by Elessar008** [comment]
Thank you for your reply！ I think so on this issue. I checked the cmakelist and found that the executables of vamp_node and vloc_node are vamp_main and vloc_main. However，the launch file run with vamp_node. 
Thank you！
Best wishes
Elessar008
